[package]
distribution = "2201.8.0"
org = "ballerinax"
name = "dayforce"
version = "0.1.1"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-dayforce"
keywords = ["HCM", "Workforce Management", "HRIS", "Vendor/DayForce", "Area/HRMS", "Type/Connector"]
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = false
